---
platform: linux

image: docker:///golang#1.7-alpine

inputs:
- name: gopath
- name: version

outputs:
- name: build-output/build

run:
  path: gopath/src/github.com/ecsteam/buildpack-usage/ci/tasks/do-build.sh
